name: streak_calculator
description: A high-performance Dart package for streak tracking—daily, weekly, or monthly. Supports custom goals, flexible week starts, and current & best streaks.

version: 0.2.0

homepage: https://github.com/abdullah-cse/streak_calculator
repository: https://github.com/abdullah-cse/streak_calculator

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0


topics:
  - streaks
  - counters
  - statistics
  - analytics
  - productivity